- name: This is touch file
  hosts: localhost
  tasks:
  - name: touch file
    command: touch /opt/verizon.txt
    when:
      - ansible_distribution == "RedHat"
      - ansible_distribution_major_version == "7"
