---
- name: This sets up an httpd webserver
  hosts: local
  vars:
      service: "httpd"
  vars_prompt:
    - name: "Package"
      prompt: "Which pachage do you want to install?"
      private: false

  tasks:
  - name: Install the httpd apps
    yum: name={{ Package }}
  - name: start the httpd service
    service: name={{ service }} state=started

