---
- hosts: localhost
  sudo: yes
  vars:
    http_port: 8080
    doc_dir: /ansible/
    doc_root: /etc/httpd/conf
    max_clients: 5

  tasks:
  - name: Ensure that Apache is installed
    yum: name=httpd state=present
    when: ansible_os_family == "RedHat"

  - name: Start Apache Services
    service: name=httpd enabled=yes state=started

  - name: Copy Site Files
    template: src=httpd.conf.j2 dest={{ doc_root }}/httpd.conf
