---
- name: This sets up an httpd server
  hosts: local
  vars_prompt:
  - name: "package"
    prompt: "Which Version?" 
    private: false
  - name: "service"
    prompt: "Which Service?"
    private: false

  tasks:
  - name: Install httpd
    yum: name={{ package }}
  - name: Start service
    service: name={{ service }} state=started

...
