---
- name: This sets up an httpd webserver
  hosts: local

  tasks:
  - name: Ansible register variable basic example
    shell: "find httpd"
    args:
      chdir: "/home/ec2-user/"
    register: find_output
  - debug:
      var: find_output.stdout
  - name: Install the httpd apps
    yum: name={{ find_output.stdout }}
  - name: start the httpd service
    service: name={{ find_output.stdout }} state=started
...

