---
- name: This sets up an httpd webserver
  hosts: Router
  vars:
    name: "Kanna"
    package: "httpd"
    service: "httpd"
  vars_prompt:
      name: "prompt"
      prompt: "what you want to prompt? "
      private: false
  
  tasks:
   - name: Install the httpd apps
     yum: name={{ package }}
   - name: start the httpd service
     service: name={{ service }} state=started
   - name: create a empty fle
     file: dest=/opt/test.txt state=touch
   - name: copy a file
     copy: dest=/var/www/html/ src="index.html"
   - name: test
     debug:
       msg: "{{name}}"
   - name: test2
     debug:
       msg: "{{prompt}}"
...

