  - name: Setting up a Webserver in localhost
    hosts: localhost
    vars_files:
        - "web_varfile.yml"

    tasks:
    - name: Install httpd package
      yum: name={{ package }} state={{ pkgstate }}

    - name: Start httpd and enable
      service: name={{ service }} state={{ ssstate }} enabled={{ ssenable }}
