---
- name: Copy file with owner and permissions
  hosts: web
  tasks:
  - name: file copy
    copy:
     src: /root/second.html
     dest: /var/www/html
     owner: root
     group: root
     mode: '0644'
...
