[root@ip-172-31-15-173 ~]# vi getvarfile.yaml
---
- name: This sets up an httpd webserver
  hosts: local
  vars:
    myname: "elumalai"
    package: "{{ myservice }}"
    service: "httpd"
  vars_files:
    - "varser.yaml"
  vars_prompt:
    - name: "httpser"
      prompt: "Which version Do you want to install?"
      private: false

  tasks:
  - name: Install the httpd apps
    yum: name={{ package }}
  - name: start the httpd service
    service: name={{ service }} state=started
  - name: create a empty fle
    file: dest=/opt/test.txt state=touch
  - name: copy a file
    copy: dest=/var/www/html/ src="index.html"
  - name: Ansible prompt example.
    debug:
      msg: "{{ myservice }}"
  - debug:
      var: find_output
  - name: Ansible vars in inventory
    debug:
      msg: "{{ myservice }}"
...
~
